[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo  = 'Shougo/context_filetype.vim'
on_ft = ['toml']

[[plugins]]
repo    = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
on_ft   = ['toml']

[[plugins]]
repo     = 'posva/vim-vue'
on_ft    = ['vue']
hook_add = '''
" コレを書いておかないとファイル途中でハイライトが消えることがある
autocmd FileType vue syntax sync fromstart
'''

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'lua', 'php', 'python', 'ruby', 'html', 'swift', 'toml', 'xml', 'yaml']

[[plugins]]
repo = 'wakatime/vim-wakatime'
on_if = 'filereadable("/root/.wakatime.cfg")'

[[plugins]]
repo     = 'mattn/emmet-vim'
on_ft    = ['css', 'less', 'scss', 'markdown', 'vue', 'php', 'html', 'erb']
hook_add = '''
" let g:user_emmet_leader_key='<Space>'
'''

